/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikumtpbo;

/**
 *
 * @author LENOVO
 */
public class Tugass1 {

    public Tugass1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NIM = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NilaiTugas = new javax.swing.JTextField();
        NilaiMid = new javax.swing.JTextField();
        NilaiSemester = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NilaiAkhir = new javax.swing.JTextField();
        NilaiHuruf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Program Aplikasi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, 36));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Perhitungan Nilai Mahasiswa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("NIM");

        jLabel4.setText("NAMA");

        NIM.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIMActionPerformed(evt);
            }
        });

        Nama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NIM, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 390, 110));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Nilai Tugas");

        jLabel6.setText("Nilai MID");

        jLabel7.setText("Nilai Semester");

        NilaiTugas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NilaiTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaiTugasActionPerformed(evt);
            }
        });

        NilaiMid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NilaiMid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaiMidActionPerformed(evt);
            }
        });

        NilaiSemester.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NilaiSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaiSemesterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NilaiMid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(NilaiSemester, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NilaiTugas))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NilaiMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NilaiSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 390, 190));

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, 30));

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Nilai Akhir");

        jLabel10.setText("Nilai Huruf");

        NilaiAkhir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NilaiAkhir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NilaiAkhirMouseClicked(evt);
            }
        });
        NilaiAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaiAkhirActionPerformed(evt);
            }
        });

        NilaiHuruf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NilaiHuruf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NilaiHurufMouseClicked(evt);
            }
        });
        NilaiHuruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NilaiHurufActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NilaiAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(NilaiHuruf))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(NilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(NilaiHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 390, 110));

        pack();
    }// </editor-fold>                        

    private void NIMActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void NilaiTugasActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {                                       
        try {
        // Mendapatkan nilai tugas, mid, dan semester dari input pengguna
        double nilaiTugas = Double.parseDouble(NilaiTugas.getText());
        double nilaiMid = Double.parseDouble(NilaiMid.getText());
        double nilaiSemester = Double.parseDouble(NilaiSemester.getText());

        // Menghitung nilai akhir
        double nilaiAkhir = (nilaiTugas * 30 / 100) + (nilaiMid * 30 / 100) + (nilaiSemester * 40 / 100);

        // Menentukan nilai huruf berdasarkan rentang nilai
        String nilaiHuruf;
        if (nilaiAkhir >= 0 && nilaiAkhir <= 100) {
            if (nilaiAkhir >= 86) {
                nilaiHuruf = "A";
            } else if (nilaiAkhir >= 81) {
                nilaiHuruf = "A-";
            } else if (nilaiAkhir >= 76) {
                nilaiHuruf = "B+";
            } else if (nilaiAkhir >= 71) {
                nilaiHuruf = "B";
            } else if (nilaiAkhir >= 66) {
                nilaiHuruf = "B-";
            } else if (nilaiAkhir >= 61) {
                nilaiHuruf = "C+";
            } else if (nilaiAkhir >= 56) {
                nilaiHuruf = "C";
            } else if (nilaiAkhir >= 41) {
                nilaiHuruf = "D";
            } else {
                nilaiHuruf = "E";
            }

            // Menampilkan hasil pada field NilaiAkhir dan NilaiHuruf
            NilaiAkhir.setText(String.valueOf(nilaiAkhir));
            NilaiHuruf.setText(nilaiHuruf);
        } else {
            // Jika nilai di luar rentang 0-100, tampilkan pesan kesalahan
            NilaiAkhir.setText("Nilai Akhir di luar rentang 0-100. Program berhenti.");
            System.exit(0);
        }
    } catch (NumberFormatException e) {
        // Tangani kesalahan jika input tidak valid
        NilaiAkhir.setText("Masukkan angka yang valid untuk nilai tugas, mid, dan semester.");
    }
    }                                      

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {                                      
    NIM.setText("");
    Nama.setText("");
    NilaiTugas.setText("");
    NilaiMid.setText("");
    NilaiSemester.setText("");
    NilaiAkhir.setText("");
    NilaiHuruf.setText("");
    }                                     

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        System.exit(0);
    }                                    

    private void NilaiAkhirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void NilaiAkhirMouseClicked(java.awt.event.MouseEvent evt) {                                        
        try {
        // Mendapatkan nilai tugas, mid, dan semester dari input pengguna
        double nilaiTugas = Double.parseDouble(NilaiTugas.getText());
        double nilaiMid = Double.parseDouble(NilaiMid.getText());
        double nilaiSemester = Double.parseDouble(NilaiSemester.getText());

        // Menghitung nilai akhir
        double nilaiAkhir = (nilaiTugas * 30 / 100) + (nilaiMid * 30 / 100) + (nilaiSemester * 40 / 100);

        // Menentukan nilai huruf berdasarkan rentang nilai
        String nilaiHuruf;
        if (nilaiAkhir >= 0 && nilaiAkhir <= 100) {
            if (nilaiAkhir >= 86) {
                nilaiHuruf = "A";
            } else if (nilaiAkhir >= 81) {
                nilaiHuruf = "A-";
            } else if (nilaiAkhir >= 76) {
                nilaiHuruf = "B+";
            } else if (nilaiAkhir >= 71) {
                nilaiHuruf = "B";
            } else if (nilaiAkhir >= 66) {
                nilaiHuruf = "B-";
            } else if (nilaiAkhir >= 61) {
                nilaiHuruf = "C+";
            } else if (nilaiAkhir >= 56) {
                nilaiHuruf = "C";
            } else if (nilaiAkhir >= 41) {
                nilaiHuruf = "D";
            } else {
                nilaiHuruf = "E";
            }

            // Menampilkan hasil pada field NilaiAkhir dan NilaiHuruf
            NilaiAkhir.setText(String.valueOf(nilaiAkhir));
            NilaiHuruf.setText(nilaiHuruf);
        } else {
            // Jika nilai di luar rentang 0-100, tampilkan pesan kesalahan
            NilaiAkhir.setText("Nilai Akhir di luar rentang 0-100. Program berhenti.");
            System.exit(0);
        }
    } catch (NumberFormatException e) {
        // Tangani kesalahan jika input tidak valid
        NilaiAkhir.setText("Masukkan angka yang valid untuk nilai tugas, mid, dan semester.");
    }
    }                                       

    private void NilaiHurufMouseClicked(java.awt.event.MouseEvent evt) {                                        
        try {
        // Mendapatkan nilai tugas, mid, dan semester dari input pengguna
        double nilaiTugas = Double.parseDouble(NilaiTugas.getText());
        double nilaiMid = Double.parseDouble(NilaiMid.getText());
        double nilaiSemester = Double.parseDouble(NilaiSemester.getText());

        // Menghitung nilai akhir
        double nilaiAkhir = (nilaiTugas * 30 / 100) + (nilaiMid * 30 / 100) + (nilaiSemester * 40 / 100);

        // Menentukan nilai huruf berdasarkan rentang nilai
        String nilaiHuruf;
        if (nilaiAkhir >= 0 && nilaiAkhir <= 100) {
            if (nilaiAkhir >= 86) {
                nilaiHuruf = "A";
            } else if (nilaiAkhir >= 81) {
                nilaiHuruf = "A-";
            } else if (nilaiAkhir >= 76) {
                nilaiHuruf = "B+";
            } else if (nilaiAkhir >= 71) {
                nilaiHuruf = "B";
            } else if (nilaiAkhir >= 66) {
                nilaiHuruf = "B-";
            } else if (nilaiAkhir >= 61) {
                nilaiHuruf = "C+";
            } else if (nilaiAkhir >= 56) {
                nilaiHuruf = "C";
            } else if (nilaiAkhir >= 41) {
                nilaiHuruf = "D";
            } else {
                nilaiHuruf = "E";
            }

            // Menampilkan hasil pada field NilaiAkhir dan NilaiHuruf
            NilaiAkhir.setText(String.valueOf(nilaiAkhir));
            NilaiHuruf.setText(nilaiHuruf);
        } else {
            // Jika nilai di luar rentang 0-100, tampilkan pesan kesalahan
            NilaiAkhir.setText("Nilai Akhir di luar rentang 0-100. Program berhenti.");
            System.exit(0);
        }
    } catch (NumberFormatException e) {
        // Tangani kesalahan jika input tidak valid
        NilaiAkhir.setText("Masukkan angka yang valid untuk nilai tugas, mid, dan semester.");
    }
    }                                       

    private void NilaiMidActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void NilaiSemesterActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void NilaiHurufActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas1().setVisible(true);
            }
        });
    }
        // Variables declaration - do not modify                     
    private javax.swing.JButton Clear;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel NIM;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel NilaiAkhir;
    private javax.swing.JLabel NilaiHuruf;
    private javax.swing.JLabel NilaiMid;
    private javax.swing.JLabel NilaiSemester;
    private javax.swing.JLabel NilaiTugas;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration                   
}
    

