/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikumtpbo;
 Connection c = null;
    PreparedStatement pst = null;
    ResultSet r = null;
    Object set;
    
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
try{
                Connection c = Koneksi.getKoneksi();
                Statement s = c.createStatement();
                String sql  = "SELECT * FROM login Where UserName=? and Password=" ;
                ResultSet r = s.executeQuery(sql);
                
                    pst = (PreparedStatement) c.prepareStatement(sql);
                    pst.setString(1, txtusername.getText());
                    pst.setString(2, txtpassword.getText());
                    r = pst.executeQuery();
                    if(r.next()){
                        JOptionPane.showMessageDialog(null, "Berhasil Login");
                        MenuUtama start = new MenuUtama();
                        start.setVisible(true);
                        this.dispose();
                    } else{
                        JOptionPane.showMessageDialog(null, "Username Atau Password Salah", "Pesan",JOptionPane.ERROR_MESSAGE);
                    }                  
                    
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    
                }

/**
 *
 * @author LENOVO
 */
public class Tugas1 extends javax.swing.JFrame {
        String UserName = "Rani";
        String password = "Rani";
        if((UserName.equals(userNameTxt.getText())
                && (password.equals(passwordTxt.getText())))){
            JOptionPane.showMessageDialog(null, "Login berhasil");
            DataBarang a = new DataBarang();
            JInternalFrame internalframe = new JInternalFrame(judul,false,true,true); 
            internalframe.setVisible(true);
            this.getDesktopPane().add(internalframe);
            
            this.dispose();       
        }else {
            JOptionPane.showMessageDialog(null, "UserName/password salah");
        }
    }                                           

    /**
     * Creates new form Tugas1
     */
    public Tugas1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NIM = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        NilaiTugas = new javax.swing.JLabel();
        NilaiMid = new javax.swing.JLabel();
        NilaiSemester = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        NilaiAkhir = new javax.swing.JLabel();
        NilaiHuruf = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Program Aplikasi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel2.setText("Perhitugan Nilai Mahasiswa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 240, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        NIM.setText("NIM");

        Nama.setText("NAMA");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nama)
                    .addComponent(NIM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIM)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 480, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        NilaiTugas.setText("Nilai Tugas");

        NilaiMid.setText("Nilai MID");

        NilaiSemester.setText("Nilai Semester");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NilaiTugas)
                    .addComponent(NilaiMid)
                    .addComponent(NilaiSemester))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NilaiTugas)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NilaiMid)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NilaiSemester)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 480, 160));

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        NilaiAkhir.setText("Nilai Akhir");

        NilaiHuruf.setText("Nilai Huruf");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NilaiAkhir)
                    .addComponent(NilaiHuruf))
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jTextField7))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NilaiAkhir)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NilaiHuruf)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 470, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void NIMActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void NilaiTugasActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                         
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
 try {
        // Mendapatkan nilai tugas, mid, dan semester dari input pengguna
        double nilaiTugas = Double.parseDouble(NilaiTugas.getText());
        double nilaiMid = Double.parseDouble(NilaiMid.getText());
        double nilaiSemester = Double.parseDouble(NilaiSemester.getText());

        // Menghitung nilai akhir
        double nilaiAkhir = (nilaiTugas * 30 / 100) + (nilaiMid * 30 / 100) + (nilaiSemester * 40 / 100);

        // Menentukan nilai huruf berdasarkan rentang nilai
        String nilaiHuruf;
        if (nilaiAkhir >= 0 && nilaiAkhir <= 100) {
            if (nilaiAkhir >= 86) {
                nilaiHuruf = "A";
            } else if (nilaiAkhir >= 81) {
                nilaiHuruf = "A-";
            } else if (nilaiAkhir >= 76) {
                nilaiHuruf = "B+";
            } else if (nilaiAkhir >= 71) {
                nilaiHuruf = "B";
            } else if (nilaiAkhir >= 66) {
                nilaiHuruf = "B-";
            } else if (nilaiAkhir >= 61) {
                nilaiHuruf = "C+";
            } else if (nilaiAkhir >= 56) {
                nilaiHuruf = "C";
            } else if (nilaiAkhir >= 41) {
                nilaiHuruf = "D";
            } else {
                nilaiHuruf = "E";
            }

            // Menampilkan hasil pada field NilaiAkhir dan NilaiHuruf
            NilaiAkhir.setText(String.valueOf(nilaiAkhir));
            NilaiHuruf.setText(nilaiHuruf);
        } else {
            // Jika nilai di luar rentang 0-100, tampilkan pesan kesalahan
            NilaiAkhir.setText("Nilai Akhir di luar rentang 0-100. Program berhenti.");
            System.exit(0);
        }
    } catch (NumberFormatException e) {
        // Tangani kesalahan jika input tidak valid
        NilaiAkhir.setText("Masukkan angka yang valid untuk nilai tugas, mid, dan semester.");
    }
    }                                      

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {                                      
    NIM.setText("");
    Nama.setText("");
    NilaiTugas.setText("");
    NilaiMid.setText("");
    NilaiSemester.setText("");
    NilaiAkhir.setText("");
    NilaiHuruf.setText("");
    }                                     

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        System.exit(0);
    }                                    

    private void NilaiAkhirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void NilaiAkhirMouseClicked(java.awt.event.MouseEvent evt) {                                        
        try {
        // Mendapatkan nilai tugas, mid, dan semester dari input pengguna
        double nilaiTugas = Double.parseDouble(NilaiTugas.getText());
        double nilaiMid = Double.parseDouble(NilaiMid.getText());
        double nilaiSemester = Double.parseDouble(NilaiSemester.getText());

        // Menghitung nilai akhir
        double nilaiAkhir = (nilaiTugas * 30 / 100) + (nilaiMid * 30 / 100) + (nilaiSemester * 40 / 100);

        // Menentukan nilai huruf berdasarkan rentang nilai
        String nilaiHuruf;
        if (nilaiAkhir >= 0 && nilaiAkhir <= 100) {
            if (nilaiAkhir >= 86) {
                nilaiHuruf = "A";
            } else if (nilaiAkhir >= 81) {
                nilaiHuruf = "A-";
            } else if (nilaiAkhir >= 76) {
                nilaiHuruf = "B+";
            } else if (nilaiAkhir >= 71) {
                nilaiHuruf = "B";
            } else if (nilaiAkhir >= 66) {
                nilaiHuruf = "B-";
            } else if (nilaiAkhir >= 61) {
                nilaiHuruf = "C+";
            } else if (nilaiAkhir >= 56) {
                nilaiHuruf = "C";
            } else if (nilaiAkhir >= 41) {
                nilaiHuruf = "D";
            } else {
                nilaiHuruf = "E";
            }

            // Menampilkan hasil pada field NilaiAkhir dan NilaiHuruf
            NilaiAkhir.setText(String.valueOf(nilaiAkhir));
            NilaiHuruf.setText(nilaiHuruf);
        } else {
            // Jika nilai di luar rentang 0-100, tampilkan pesan kesalahan
            NilaiAkhir.setText("Nilai Akhir di luar rentang 0-100. Program berhenti.");
            System.exit(0);
        }
    } catch (NumberFormatException e) {
        // Tangani kesalahan jika input tidak valid
        NilaiAkhir.setText("Masukkan angka yang valid untuk nilai tugas, mid, dan semester.");
    }
                                           // TODO add your handling code here:    
    }//GEN-LAST:event_SubmitActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
    NIM.setText("");
    Nama.setText("");
    NilaiTugas.setText("");
    NilaiMid.setText("");
    NilaiSemester.setText("");
    NilaiAkhir.setText("");
    NilaiHuruf.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {                                     
        System.exit(0);
    }                                    

    private void NilaiAkhirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void NilaiAkhirMouseClicked(java.awt.event.MouseEvent evt) {                                        
        try {
        // Mendapatkan nilai tugas, mid, dan semester dari input pengguna
        double nilaiTugas = Double.parseDouble(NilaiTugas.getText());
        double nilaiMid = Double.parseDouble(NilaiMid.getText());
        double nilaiSemester = Double.parseDouble(NilaiSemester.getText());

        // Menghitung nilai akhir
        double nilaiAkhir = (nilaiTugas * 30 / 100) + (nilaiMid * 30 / 100) + (nilaiSemester * 40 / 100);

        // Menentukan nilai huruf berdasarkan rentang nilai
        String nilaiHuruf;
        if (nilaiAkhir >= 0 && nilaiAkhir <= 100) {
            if (nilaiAkhir >= 86) {
                nilaiHuruf = "A";
            } else if (nilaiAkhir >= 81) {
                nilaiHuruf = "A-";
            } else if (nilaiAkhir >= 76) {
                nilaiHuruf = "B+";
            } else if (nilaiAkhir >= 71) {
                nilaiHuruf = "B";
            } else if (nilaiAkhir >= 66) {
                nilaiHuruf = "B-";
            } else if (nilaiAkhir >= 61) {
                nilaiHuruf = "C+";
            } else if (nilaiAkhir >= 56) {
                nilaiHuruf = "C";
            } else if (nilaiAkhir >= 41) {
                nilaiHuruf = "D";
            } else {
                nilaiHuruf = "E";
            }

            // Menampilkan hasil pada field NilaiAkhir dan NilaiHuruf
            NilaiAkhir.setText(String.valueOf(nilaiAkhir));
            NilaiHuruf.setText(nilaiHuruf);
        } else {
            // Jika nilai di luar rentang 0-100, tampilkan pesan kesalahan
            NilaiAkhir.setText("Nilai Akhir di luar rentang 0-100. Program berhenti.");
            System.exit(0);
        }
    } catch (NumberFormatException e) {
        // Tangani kesalahan jika input tidak valid
        NilaiAkhir.setText("Masukkan angka yang valid untuk nilai tugas, mid, dan semester.");
    }
    }                                       

    private void NilaiHurufMouseClicked(java.awt.event.MouseEvent evt) {                                        
        try {
        // Mendapatkan nilai tugas, mid, dan semester dari input pengguna
        double nilaiTugas = Double.parseDouble(NilaiTugas.getText());
        double nilaiMid = Double.parseDouble(NilaiMid.getText());
        double nilaiSemester = Double.parseDouble(NilaiSemester.getText());

        // Menghitung nilai akhir
        double nilaiAkhir = (nilaiTugas * 30 / 100) + (nilaiMid * 30 / 100) + (nilaiSemester * 40 / 100);

        // Menentukan nilai huruf berdasarkan rentang nilai
        String nilaiHuruf;
        if (nilaiAkhir >= 0 && nilaiAkhir <= 100) {
            if (nilaiAkhir >= 86) {
                nilaiHuruf = "A";
            } else if (nilaiAkhir >= 81) {
                nilaiHuruf = "A-";
            } else if (nilaiAkhir >= 76) {
                nilaiHuruf = "B+";
            } else if (nilaiAkhir >= 71) {
                nilaiHuruf = "B";
            } else if (nilaiAkhir >= 66) {
                nilaiHuruf = "B-";
            } else if (nilaiAkhir >= 61) {
                nilaiHuruf = "C+";
            } else if (nilaiAkhir >= 56) {
                nilaiHuruf = "C";
            } else if (nilaiAkhir >= 41) {
                nilaiHuruf = "D";
            } else {
                nilaiHuruf = "E";
            }

            // Menampilkan hasil pada field NilaiAkhir dan NilaiHuruf
            NilaiAkhir.setText(String.valueOf(nilaiAkhir));
            NilaiHuruf.setText(nilaiHuruf);
        } else {
            // Jika nilai di luar rentang 0-100, tampilkan pesan kesalahan
            NilaiAkhir.setText("Nilai Akhir di luar rentang 0-100. Program berhenti.");
            System.exit(0);
        }
    } catch (NumberFormatException e) {
        // Tangani kesalahan jika input tidak valid
        NilaiAkhir.setText("Masukkan angka yang valid untuk nilai tugas, mid, dan semester.");
    }
    }                                       

    private void NilaiMidActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void NilaiSemesterActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void NilaiHurufActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas1().setVisible(true);
   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel NIM;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel NilaiAkhir;
    private javax.swing.JLabel NilaiHuruf;
    private javax.swing.JLabel NilaiMid;
    private javax.swing.JLabel NilaiSemester;
    private javax.swing.JLabel NilaiTugas;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
